### ISSUE TITLE
Team Member Creates Available Time Slot through Calendar Invitation

### ISSUE THREAD

**Issue by maximegalon5** [zinc-collective/support#13]
```features/scheduling-availabilty.feature
Feature: Scheduling Availability
  In order to signal availability for conversations
  As a Team Member
  I want to make my availability visible by blocking out time on my calendar


  @wip
  Scenario: Team Member Creates Available Time Slot through Calendar Invitation
    Given a Team Member with a Public Schedule Link
    When the Team Member invites their Appointment Slots Email to an event on their preferred Calendar application
    Then the Available Time Slot is shown on the Team Member's Public Schedule Link
```

## This Issue May Be Closed When
- [x] The scenario is in the codebase without being wired in
- [ ] The scenario is wired in to test the system
- [ ] The scenario passes in CI
- [ ] The scenario is confirmed in production by a maintainer.
- [ ] The client-facing documentation includes written instructions for marking yourself as available. <link to google doc here?>
- [ ] A short blurb about the feature is published in release notes.
> Earmark your office hours or availability for conversations in your own calendar!  Invite your [availability email](#link-to-scheduling-settings-page) and we'll  update your scheduling page with your new availability!

**Comment by zspencer** [comment]
How does this sound from a "Short Blurb for Release Notes:"

```RELEASE-NOTES.md
**New Feature: App-Free Scheduling!** It's tough balancing being available
for conversations with having focused time. Our new App-Free scheduling
feature _works with your existing calendar of choice!_ 

Invite your [availability email](#link-to-scheduling-settings-page) and we'll 
automatically update your scheduling link with your new availability. 

Need to cancel a time slot? Delete it from your calendar! It'll disappear from 
your scheduling page lickety split!
```

(Perhaps figuring out the release note message deserves it's own ticket, so the more wordsmithy focused folks can focus on it)

**Comment by maximegalon5** [comment]
There's a shift in behavior here which I think we should try and test too. User Experience? For example, the Team Member is going from an On-Demand Availability paradigm to one where the Team Member is Making Themselves Selectively Available akin to Office Hours. The Motivation here is different. The TAVI / Hooked framework will be different too.

**Comment by maximegalon5** [comment]
> ```lisp
> Invite your [availability email](#link-to-scheduling-settings-page) and we'll 
> automatically update your scheduling link with your new availability. 
> ```

Perhaps we should highlight the workflow ie 

```
Earmark your availability for conversations in your own calendar, invite your [availability email](#link-to-scheduling-settings-page) and we'll automatically update your Public scheduling link with your new availability. 
```

**Comment by zspencer** [comment]
I dig it! Updated the top-level issue with

```
Earmark your office hours or availability for conversations in your own calendar! 
Invite your [availability email](#link-to-scheduling-settings-page) and we'll 
update your scheduling page with your new availability!
```
