### ISSUE TITLE
Scenario: Team Member Creates New Available Time Slots in App

### ISSUE THREAD

**Issue by maximegalon5** [zinc-collective/support#14]
```features/scheduling.feature
  Scenario: Team Member Creates New Available Time Slots in App
    Given a Team Member without a Calendar Connection
    When the Team Member defines an Available Time Slot within the App
   Then an email is sent to the Team Member's email address with an iCal file for the new Available Time Slot
    And the new Available Time Slot is shown on the Team Member's Public Schedule Link
```

### This Issue May Be Closed When
- [ ] There is a help doc describing how to schedule availability within the app.
- [ ] The feature is deployed to production for all users.
- [ ] The feature has been announced in the WGYBT feature announcement channel(s).
