### ISSUE TITLE
Support Team Member sends Templated Response from their Inbox

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/support#21]
In order to keep our communications consistent
As a maintainer
I would like to be able to use a templated response from the Support Inbox

## This Issue May Be Closed When
- [ ] A set of scenarios that describe the use-case have been added to `features/responding-to-messages.feature`
- [ ] Low-or-high fidelity mockups have been created that illustrate the user interface and workflow for the use-case and are stored within the project repository
- [ ] A client-owner has verified the use cases function as expected in production
- [ ] The feature has been announced to the Support clients mailing list.

### Examples:

```
Thank you for your feedback! 

As you may (or may not!) know, the Movie Looks app is maintained by a team of volunteer software designers, programmers, and support team members who split the revenue generated from sales of the apps between ourselves and invest our spare time and attention keeping the apps working in modern iOS devices and making small improvements where we can.

I've created more formal feature requests to help direct our volunteer community in their efforts:

1. Videographer may apply the MovieLooks filter to a number of clips at the same time - https://github.com/zinc-collective/mp-movielooks/issues/1
2. Videographer may apply the MovieLooks filter when working within other iOS apps - https://github.com/zinc-collective/mp-movielooks/issues/2
3. Videographer may apply a "mask" to adjust the effect on part of the image - https://github.com/zinc-collective/mp-movielooks/issues/3

Re: Masking - Can you link to the kinds of masks you are interested in?
Re: Film-Grain emulations - Could you link to examples of the kinds of grain you are interested in?

At present, the full collection of Moment Park brings in approximately $500 per quarter in revenue.You can see our full financial reports for Q1 2020 here: https://www.zinc.coop/financial-reports/#2020-q1-profit-and-loss

That said, there are a number of ways that members of our client community (that's you!) can help us accelerate our development efforts: 

1. Contributing your time, attention, and expertise to improving the Movie Looks project, whose source code is publicly available here: https://github.com/zinc-collective/mp-movielooks/. See https://www.zinc.coop/contributing/ for documentation on how to begin contributing.
2. Encouraging their designer and programmer friends to contribute their own time, attention, and expertise.
3. Spending money directly to direct our efforts extending our portfolio of products. The rate is $135USD per hour, and we would want to take some time to figure out the appropriate budget and timeline for execution.
4. Backing or sponsoring our Open Collective, https://opencollective.com/moment-park (You'd be the first one!)

Of course, we never want anyone to contribute time, attention, expertise, or money that would put them in a socioeconomically unsustainable position or that would bring resentment. There is absolutely 100% _zero_ pressure from us for you to perform any of those actions, but they _would_ help us build your feature requests faster.
```
